# consul服务端口号
server:
  port: 8006

# windows启动consul，以开发模式启动
# consul agent -dev

spring:
  application:
    name: consul-provider-payment
    #consul注册中心地址
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}

